In [1]:
print("Peddireddy")

Peddireddy


In [ ]:
for i in range(10):
    print(i)

In [ ]:
from notebook.auth import *

In [1]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)

arr2d = np.array([[1,2,4],[5,6,7]])
print(arr2d)

[1 2 3 4 5]
[[1 2 4]
 [5 6 7]]


In [2]:
list1 = [1,2,3,4,5,6]
print(list1)

[1, 2, 3, 4, 5, 6]
